version: '3.8'

services:
  drf:
    build: .
    container_name: drf
    image: backend
    restart: always
    command: ["python", "manage.py", "runserver",
              "0.0.0.0:8000"]
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: db
    restart: always
    volumes:
      - data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:7.0
    container_name: redis

  celery_worker:
    build: .
    container_name: worker
    image: celery_worker
    command: celery -A drive_hub worker -l info
    volumes: 
      - .:/app
    env_file:
      - .env
    depends_on:
      - drf
      - redis

  celery_beat:
    build: .
    container_name: scheduler
    image: celery_beat
    command: ["celery", "-A", "drive_hub", 
    		      "beat", "-l", "info"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - drf
      - redis

volumes:
  data:
